### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by e-spaulding**

### CODE REVIEW

**Comment by aphedges** [comment]
This replaces qnodes in DWD with versions that are only in Wikidata, so it will likely cause problems for us.

**Comment by aphedges** [comment]
A user browsing Wikidata wouldn't be affected by following a redirect, but that information simply isn't in DWD, so anyone relying on DWD can no longer use these entries.

**Comment by aphedges** [comment]
Looking more into this, I'm a little confused. It seems you have multiple versions for some qnodes, such as `Q11868838` and `Q11620540`. The former is in DWD and is a redirect in Wikidata, while the latter is in only Wikidata. Is this intentional?

**Comment by e-spaulding** [comment]
Argh. Sorry about this. What happened was, we had both DWD_Q11868838 and DWD_Q11620540 in the overlay (with one Qnode id redirecting to the other) at the same time. I had been asked to fix it last minute and tried to hurry out another release and just went with the most recent WD identifier I could find for each duplicate. I'll try to do one more fix.

**Comment by aphedges** [comment]
I found some other things that need changing, but I didn't get a chance to write up an issue yet. I'll be posting it shortly.

**Pull request merged**
